### ISSUE TITLE
Recaptured Image Forensic

### ISSUE THREAD

**Issue by kudoNCT** [manjaryp/GANvsGraphicsvsReal#1]
Dear author, congratulate your work !  
Have you try applying this method for recaptured image detection problem ? Can I train this model with recapture image dataset ? Thank you for your sharing.

**Comment by anoopkadan** [comment]
Thanks.
This is the link to the published version of the work. https://www.sciencedirect.com/science/article/abs/pii/S2214212622001247 
We have not yet tried this method for recaptured image detection, but we hope this can also be utilized to train on recapture images.
